### ISSUE TITLE
Parse error

### ISSUE THREAD

**Issue by Thrinadh360** [WebCrew/HumHub-WeChat#2]
This module was successfully installed but when i click on wechat settings, it shows Parse error.
Help me in this regard.

**Comment by Felli** [comment]
Please provide a full error stack so that I can better understand the issue you're having.

**Comment by WebCrew** [comment]
I think it has something to do with the module admin controller. Maybe the module must be updated to fit latest HumHub standards. I`m not up to date with HumHub because I stoped developing modules/themes for it and also stoped using it. Maybe @Felli can check if HumHub got updates with the module system.

**Comment by Felli** [comment]
Should be working now with c0417e51cb457a0b4d19e440b750c7b454546207 my updating kind of broke it with 3ec67cc0999e34baed91c2c7c265c70f873a6015

**Comment by WebCrew** [comment]
Yeah good work @Felli :1st_place_medal:

**Comment by Felli** [comment]
Also fixed an issue for language translation breaking site.

**Comment by WebCrew** [comment]
Nice job @Felli .... **I`m happy you take a look onto the modules** otherwise all the work was for nothing.
Kind regards :)

**Comment by WebCrew** [comment]
@Thrinadh360 would you be so kind and check if the bug is gone now? I think the module is working again thx to @Felli
